export interface SubtitleLine {
  id: number;
  startTime: number; // seconds
  endTime: number;
  originalText: string;
  translatedText: string;
  words: SubtitleWord[];
}

// Type alias for compatibility
export type Subtitle = SubtitleLine;

export interface SubtitleWord {
  text: string;
  startIndex: number;
  endIndex: number;
  saved: boolean;
  difficulty?: "beginner" | "intermediate" | "advanced";
  translation?: string;
  definition?: string;
}

export const mockSubtitles: SubtitleLine[] = [
  {
    id: 1,
    startTime: 0,
    endTime: 3.5,
    originalText: "What makes you happy in life?",
    translatedText: "生活中什么让你快乐？",
    words: [
      { text: "What", startIndex: 0, endIndex: 4, saved: false },
      { text: "makes", startIndex: 5, endIndex: 10, saved: true, difficulty: "beginner", translation: "使得", definition: "to cause something to happen" },
      { text: "you", startIndex: 11, endIndex: 14, saved: false },
      { text: "happy", startIndex: 15, endIndex: 20, saved: true, difficulty: "beginner", translation: "快乐的", definition: "feeling pleasure and enjoyment" },
      { text: "in", startIndex: 21, endIndex: 23, saved: false },
      { text: "life", startIndex: 24, endIndex: 28, saved: true, difficulty: "intermediate", translation: "生活", definition: "the existence of a person" },
    ],
  },
  {
    id: 2,
    startTime: 4,
    endTime: 7,
    originalText: "I think spending time with my family.",
    translatedText: "我认为是和家人在一起的时光。",
    words: [
      { text: "I", startIndex: 0, endIndex: 1, saved: false },
      { text: "think", startIndex: 2, endIndex: 7, saved: false },
      { text: "spending", startIndex: 8, endIndex: 16, saved: true, difficulty: "intermediate", translation: "花费", definition: "to use time doing something" },
      { text: "time", startIndex: 17, endIndex: 21, saved: false },
      { text: "with", startIndex: 22, endIndex: 26, saved: false },
      { text: "my", startIndex: 27, endIndex: 29, saved: false },
      { text: "family", startIndex: 30, endIndex: 36, saved: true, difficulty: "beginner", translation: "家庭", definition: "a group of people related by blood or marriage" },
    ],
  },
  {
    id: 3,
    startTime: 7.5,
    endTime: 11,
    originalText: "That's wonderful. Family is so important.",
    translatedText: "太好了。家庭非常重要。",
    words: [
      { text: "That's", startIndex: 0, endIndex: 6, saved: false },
      { text: "wonderful", startIndex: 7, endIndex: 16, saved: true, difficulty: "intermediate", translation: "美好的", definition: "extremely good or pleasant" },
      { text: "Family", startIndex: 18, endIndex: 24, saved: true, difficulty: "beginner", translation: "家庭", definition: "a group of people related by blood or marriage" },
      { text: "is", startIndex: 25, endIndex: 27, saved: false },
      { text: "so", startIndex: 28, endIndex: 30, saved: false },
      { text: "important", startIndex: 31, endIndex: 40, saved: true, difficulty: "intermediate", translation: "重要的", definition: "having great significance or value" },
    ],
  },
  {
    id: 4,
    startTime: 11.5,
    endTime: 14.5,
    originalText: "Do you have any hobbies?",
    translatedText: "你有什么爱好吗？",
    words: [
      { text: "Do", startIndex: 0, endIndex: 2, saved: false },
      { text: "you", startIndex: 3, endIndex: 6, saved: false },
      { text: "have", startIndex: 7, endIndex: 11, saved: false },
      { text: "any", startIndex: 12, endIndex: 15, saved: false },
      { text: "hobbies", startIndex: 16, endIndex: 23, saved: true, difficulty: "beginner", translation: "爱好", definition: "activities done regularly for pleasure" },
    ],
  },
  {
    id: 5,
    startTime: 15,
    endTime: 18,
    originalText: "Yes, I love reading books.",
    translatedText: "是的，我喜欢读书。",
    words: [
      { text: "Yes", startIndex: 0, endIndex: 3, saved: false },
      { text: "I", startIndex: 5, endIndex: 6, saved: false },
      { text: "love", startIndex: 7, endIndex: 11, saved: true, difficulty: "beginner", translation: "喜爱", definition: "to have a strong affection for" },
      { text: "reading", startIndex: 12, endIndex: 19, saved: true, difficulty: "beginner", translation: "阅读", definition: "the action of reading books" },
      { text: "books", startIndex: 20, endIndex: 25, saved: false },
    ],
  },
  {
    id: 6,
    startTime: 18.5,
    endTime: 22,
    originalText: "What kind of books do you enjoy?",
    translatedText: "你喜欢什么类型的书？",
    words: [
      { text: "What", startIndex: 0, endIndex: 4, saved: false },
      { text: "kind", startIndex: 5, endIndex: 9, saved: false },
      { text: "of", startIndex: 10, endIndex: 12, saved: false },
      { text: "books", startIndex: 13, endIndex: 18, saved: false },
      { text: "do", startIndex: 19, endIndex: 21, saved: false },
      { text: "you", startIndex: 22, endIndex: 25, saved: false },
      { text: "enjoy", startIndex: 26, endIndex: 31, saved: true, difficulty: "beginner", translation: "享受", definition: "to take pleasure in something" },
    ],
  },
  {
    id: 7,
    startTime: 22.5,
    endTime: 26,
    originalText: "I prefer science fiction and mystery novels.",
    translatedText: "我更喜欢科幻小说和悬疑小说。",
    words: [
      { text: "I", startIndex: 0, endIndex: 1, saved: false },
      { text: "prefer", startIndex: 2, endIndex: 8, saved: true, difficulty: "intermediate", translation: "更喜欢", definition: "to like something better than another" },
      { text: "science", startIndex: 9, endIndex: 16, saved: false },
      { text: "fiction", startIndex: 17, endIndex: 24, saved: true, difficulty: "intermediate", translation: "小说", definition: "literature in the form of prose" },
      { text: "and", startIndex: 25, endIndex: 28, saved: false },
      { text: "mystery", startIndex: 29, endIndex: 36, saved: true, difficulty: "intermediate", translation: "神秘", definition: "something difficult to understand" },
      { text: "novels", startIndex: 37, endIndex: 43, saved: false },
    ],
  },
  {
    id: 8,
    startTime: 26.5,
    endTime: 30,
    originalText: "That sounds interesting. Do you read every day?",
    translatedText: "听起来很有趣。你每天都读书吗？",
    words: [
      { text: "That", startIndex: 0, endIndex: 4, saved: false },
      { text: "sounds", startIndex: 5, endIndex: 11, saved: false },
      { text: "interesting", startIndex: 12, endIndex: 23, saved: true, difficulty: "intermediate", translation: "有趣的", definition: "arousing curiosity or interest" },
      { text: "Do", startIndex: 25, endIndex: 27, saved: false },
      { text: "you", startIndex: 28, endIndex: 31, saved: false },
      { text: "read", startIndex: 32, endIndex: 36, saved: false },
      { text: "every", startIndex: 37, endIndex: 42, saved: false },
      { text: "day", startIndex: 43, endIndex: 46, saved: false },
    ],
  },
  {
    id: 9,
    startTime: 30.5,
    endTime: 34,
    originalText: "I try to read at least one chapter before bed.",
    translatedText: "我尽量在睡前至少读一章。",
    words: [
      { text: "I", startIndex: 0, endIndex: 1, saved: false },
      { text: "try", startIndex: 2, endIndex: 5, saved: false },
      { text: "to", startIndex: 6, endIndex: 8, saved: false },
      { text: "read", startIndex: 9, endIndex: 13, saved: false },
      { text: "at", startIndex: 14, endIndex: 16, saved: false },
      { text: "least", startIndex: 17, endIndex: 22, saved: true, difficulty: "intermediate", translation: "至少", definition: "at the minimum" },
      { text: "one", startIndex: 23, endIndex: 26, saved: false },
      { text: "chapter", startIndex: 27, endIndex: 34, saved: true, difficulty: "intermediate", translation: "章节", definition: "a main division of a book" },
      { text: "before", startIndex: 35, endIndex: 41, saved: false },
      { text: "bed", startIndex: 42, endIndex: 45, saved: false },
    ],
  },
  {
    id: 10,
    startTime: 34.5,
    endTime: 38,
    originalText: "That's a great habit to have.",
    translatedText: "这是一个很好的习惯。",
    words: [
      { text: "That's", startIndex: 0, endIndex: 6, saved: false },
      { text: "a", startIndex: 7, endIndex: 8, saved: false },
      { text: "great", startIndex: 9, endIndex: 14, saved: true, difficulty: "beginner", translation: "很好的", definition: "of an extent, amount, or intensity considerably above average" },
      { text: "habit", startIndex: 15, endIndex: 20, saved: true, difficulty: "intermediate", translation: "习惯", definition: "a settled or regular tendency or practice" },
      { text: "to", startIndex: 21, endIndex: 23, saved: false },
      { text: "have", startIndex: 24, endIndex: 28, saved: false },
    ],
  },
  {
    id: 11,
    startTime: 38.5,
    endTime: 42,
    originalText: "Reading helps me relax after a long day.",
    translatedText: "阅读帮助我在漫长的一天后放松。",
    words: [
      { text: "Reading", startIndex: 0, endIndex: 7, saved: true, difficulty: "beginner", translation: "阅读", definition: "the action of reading" },
      { text: "helps", startIndex: 8, endIndex: 13, saved: false },
      { text: "me", startIndex: 14, endIndex: 16, saved: false },
      { text: "relax", startIndex: 17, endIndex: 22, saved: true, difficulty: "intermediate", translation: "放松", definition: "to become less tense or anxious" },
      { text: "after", startIndex: 23, endIndex: 28, saved: false },
      { text: "a", startIndex: 29, endIndex: 30, saved: false },
      { text: "long", startIndex: 31, endIndex: 35, saved: false },
      { text: "day", startIndex: 36, endIndex: 39, saved: false },
    ],
  },
  {
    id: 12,
    startTime: 42.5,
    endTime: 46,
    originalText: "Do you prefer physical books or e-books?",
    translatedText: "你更喜欢纸质书还是电子书？",
    words: [
      { text: "Do", startIndex: 0, endIndex: 2, saved: false },
      { text: "you", startIndex: 3, endIndex: 6, saved: false },
      { text: "prefer", startIndex: 7, endIndex: 13, saved: true, difficulty: "intermediate", translation: "更喜欢", definition: "to like better" },
      { text: "physical", startIndex: 14, endIndex: 22, saved: true, difficulty: "intermediate", translation: "实体的", definition: "relating to things perceived through the senses" },
      { text: "books", startIndex: 23, endIndex: 28, saved: false },
      { text: "or", startIndex: 29, endIndex: 31, saved: false },
      { text: "e-books", startIndex: 32, endIndex: 39, saved: true, difficulty: "beginner", translation: "电子书", definition: "electronic books" },
    ],
  },
  {
    id: 13,
    startTime: 46.5,
    endTime: 50,
    originalText: "I still love the feel of a real book.",
    translatedText: "我仍然喜欢真实书籍的感觉。",
    words: [
      { text: "I", startIndex: 0, endIndex: 1, saved: false },
      { text: "still", startIndex: 2, endIndex: 7, saved: false },
      { text: "love", startIndex: 8, endIndex: 12, saved: true, difficulty: "beginner", translation: "喜爱", definition: "to have strong affection for" },
      { text: "the", startIndex: 13, endIndex: 16, saved: false },
      { text: "feel", startIndex: 17, endIndex: 21, saved: true, difficulty: "beginner", translation: "感觉", definition: "the sensation of touch" },
      { text: "of", startIndex: 22, endIndex: 24, saved: false },
      { text: "a", startIndex: 25, endIndex: 26, saved: false },
      { text: "real", startIndex: 27, endIndex: 31, saved: false },
      { text: "book", startIndex: 32, endIndex: 36, saved: false },
    ],
  },
  {
    id: 14,
    startTime: 50.5,
    endTime: 54,
    originalText: "There's something special about turning pages.",
    translatedText: "翻页有一种特别的感觉。",
    words: [
      { text: "There's", startIndex: 0, endIndex: 7, saved: false },
      { text: "something", startIndex: 8, endIndex: 17, saved: false },
      { text: "special", startIndex: 18, endIndex: 25, saved: true, difficulty: "beginner", translation: "特别的", definition: "better, greater, or otherwise different from what is usual" },
      { text: "about", startIndex: 26, endIndex: 31, saved: false },
      { text: "turning", startIndex: 32, endIndex: 39, saved: true, difficulty: "beginner", translation: "翻转", definition: "to move in a circular direction" },
      { text: "pages", startIndex: 40, endIndex: 45, saved: false },
    ],
  },
  {
    id: 15,
    startTime: 54.5,
    endTime: 58,
    originalText: "I completely understand that feeling.",
    translatedText: "我完全理解那种感觉。",
    words: [
      { text: "I", startIndex: 0, endIndex: 1, saved: false },
      { text: "completely", startIndex: 2, endIndex: 12, saved: true, difficulty: "intermediate", translation: "完全地", definition: "totally; utterly" },
      { text: "understand", startIndex: 13, endIndex: 23, saved: true, difficulty: "beginner", translation: "理解", definition: "to perceive the intended meaning" },
      { text: "that", startIndex: 24, endIndex: 28, saved: false },
      { text: "feeling", startIndex: 29, endIndex: 36, saved: false },
    ],
  },
  {
    id: 16,
    startTime: 58.5,
    endTime: 62,
    originalText: "What's the last book you read?",
    translatedText: "你最近读的是什么书？",
    words: [
      { text: "What's", startIndex: 0, endIndex: 6, saved: false },
      { text: "the", startIndex: 7, endIndex: 10, saved: false },
      { text: "last", startIndex: 11, endIndex: 15, saved: false },
      { text: "book", startIndex: 16, endIndex: 20, saved: false },
      { text: "you", startIndex: 21, endIndex: 24, saved: false },
      { text: "read", startIndex: 25, endIndex: 29, saved: false },
    ],
  },
  {
    id: 17,
    startTime: 62.5,
    endTime: 66,
    originalText: "I just finished a thriller by Agatha Christie.",
    translatedText: "我刚读完阿加莎·克里斯蒂的一本惊悚小说。",
    words: [
      { text: "I", startIndex: 0, endIndex: 1, saved: false },
      { text: "just", startIndex: 2, endIndex: 6, saved: false },
      { text: "finished", startIndex: 7, endIndex: 15, saved: true, difficulty: "beginner", translation: "完成", definition: "to bring to an end" },
      { text: "a", startIndex: 16, endIndex: 17, saved: false },
      { text: "thriller", startIndex: 18, endIndex: 26, saved: true, difficulty: "intermediate", translation: "惊悚小说", definition: "a novel or play depicting an exciting plot" },
      { text: "by", startIndex: 27, endIndex: 29, saved: false },
      { text: "Agatha", startIndex: 30, endIndex: 36, saved: false },
      { text: "Christie", startIndex: 37, endIndex: 45, saved: false },
    ],
  },
  {
    id: 18,
    startTime: 66.5,
    endTime: 70,
    originalText: "Oh, I love her mysteries!",
    translatedText: "哦，我喜欢她的悬疑小说！",
    words: [
      { text: "Oh", startIndex: 0, endIndex: 2, saved: false },
      { text: "I", startIndex: 4, endIndex: 5, saved: false },
      { text: "love", startIndex: 6, endIndex: 10, saved: true, difficulty: "beginner", translation: "喜爱", definition: "to have strong affection for" },
      { text: "her", startIndex: 11, endIndex: 14, saved: false },
      { text: "mysteries", startIndex: 15, endIndex: 24, saved: true, difficulty: "intermediate", translation: "悬疑作品", definition: "novels dealing with puzzling crimes" },
    ],
  },
  {
    id: 19,
    startTime: 70.5,
    endTime: 74,
    originalText: "Which one did you read?",
    translatedText: "你读的是哪一本？",
    words: [
      { text: "Which", startIndex: 0, endIndex: 5, saved: false },
      { text: "one", startIndex: 6, endIndex: 9, saved: false },
      { text: "did", startIndex: 10, endIndex: 13, saved: false },
      { text: "you", startIndex: 14, endIndex: 17, saved: false },
      { text: "read", startIndex: 18, endIndex: 22, saved: false },
    ],
  },
  {
    id: 20,
    startTime: 74.5,
    endTime: 78,
    originalText: "Murder on the Orient Express.",
    translatedText: "《东方快车谋杀案》。",
    words: [
      { text: "Murder", startIndex: 0, endIndex: 6, saved: true, difficulty: "intermediate", translation: "谋杀", definition: "the unlawful killing of a person" },
      { text: "on", startIndex: 7, endIndex: 9, saved: false },
      { text: "the", startIndex: 10, endIndex: 13, saved: false },
      { text: "Orient", startIndex: 14, endIndex: 20, saved: false },
      { text: "Express", startIndex: 21, endIndex: 28, saved: false },
    ],
  },
  {
    id: 21,
    startTime: 78.5,
    endTime: 82,
    originalText: "That's a classic! The plot twist is amazing.",
    translatedText: "那是经典之作！情节转折太精彩了。",
    words: [
      { text: "That's", startIndex: 0, endIndex: 6, saved: false },
      { text: "a", startIndex: 7, endIndex: 8, saved: false },
      { text: "classic", startIndex: 9, endIndex: 16, saved: true, difficulty: "intermediate", translation: "经典", definition: "judged over a period of time to be of the highest quality" },
      { text: "The", startIndex: 18, endIndex: 21, saved: false },
      { text: "plot", startIndex: 22, endIndex: 26, saved: true, difficulty: "intermediate", translation: "情节", definition: "the main events of a story" },
      { text: "twist", startIndex: 27, endIndex: 32, saved: true, difficulty: "intermediate", translation: "转折", definition: "an unexpected development" },
      { text: "is", startIndex: 33, endIndex: 35, saved: false },
      { text: "amazing", startIndex: 36, endIndex: 43, saved: true, difficulty: "beginner", translation: "惊人的", definition: "causing great surprise or wonder" },
    ],
  },
  {
    id: 22,
    startTime: 82.5,
    endTime: 86,
    originalText: "I couldn't put it down once I started.",
    translatedText: "一旦开始读就停不下来。",
    words: [
      { text: "I", startIndex: 0, endIndex: 1, saved: false },
      { text: "couldn't", startIndex: 2, endIndex: 10, saved: false },
      { text: "put", startIndex: 11, endIndex: 14, saved: false },
      { text: "it", startIndex: 15, endIndex: 17, saved: false },
      { text: "down", startIndex: 18, endIndex: 22, saved: false },
      { text: "once", startIndex: 23, endIndex: 27, saved: false },
      { text: "I", startIndex: 28, endIndex: 29, saved: false },
      { text: "started", startIndex: 30, endIndex: 37, saved: false },
    ],
  },
  {
    id: 23,
    startTime: 86.5,
    endTime: 90,
    originalText: "Do you have any recommendations for me?",
    translatedText: "你有什么推荐给我的吗？",
    words: [
      { text: "Do", startIndex: 0, endIndex: 2, saved: false },
      { text: "you", startIndex: 3, endIndex: 6, saved: false },
      { text: "have", startIndex: 7, endIndex: 11, saved: false },
      { text: "any", startIndex: 12, endIndex: 15, saved: false },
      { text: "recommendations", startIndex: 16, endIndex: 31, saved: true, difficulty: "intermediate", translation: "推荐", definition: "suggestions as to the best course of action" },
      { text: "for", startIndex: 32, endIndex: 35, saved: false },
      { text: "me", startIndex: 36, endIndex: 38, saved: false },
    ],
  },
  {
    id: 24,
    startTime: 90.5,
    endTime: 94,
    originalText: "You should try 'And Then There Were None'.",
    translatedText: "你应该试试《无人生还》。",
    words: [
      { text: "You", startIndex: 0, endIndex: 3, saved: false },
      { text: "should", startIndex: 4, endIndex: 10, saved: false },
      { text: "try", startIndex: 11, endIndex: 14, saved: false },
      { text: "And", startIndex: 16, endIndex: 19, saved: false },
      { text: "Then", startIndex: 20, endIndex: 24, saved: false },
      { text: "There", startIndex: 25, endIndex: 30, saved: false },
      { text: "Were", startIndex: 31, endIndex: 35, saved: false },
      { text: "None", startIndex: 36, endIndex: 40, saved: false },
    ],
  },
  {
    id: 25,
    startTime: 94.5,
    endTime: 98,
    originalText: "It's considered her masterpiece.",
    translatedText: "这被认为是她的杰作。",
    words: [
      { text: "It's", startIndex: 0, endIndex: 4, saved: false },
      { text: "considered", startIndex: 5, endIndex: 15, saved: true, difficulty: "intermediate", translation: "被认为", definition: "to think carefully about" },
      { text: "her", startIndex: 16, endIndex: 19, saved: false },
      { text: "masterpiece", startIndex: 20, endIndex: 31, saved: true, difficulty: "advanced", translation: "杰作", definition: "a work of outstanding artistry or skill" },
    ],
  },
  {
    id: 26,
    startTime: 98.5,
    endTime: 102,
    originalText: "Thanks! I'll add it to my reading list.",
    translatedText: "谢谢！我会把它加到我的阅读清单。",
    words: [
      { text: "Thanks", startIndex: 0, endIndex: 6, saved: false },
      { text: "I'll", startIndex: 8, endIndex: 12, saved: false },
      { text: "add", startIndex: 13, endIndex: 16, saved: true, difficulty: "beginner", translation: "添加", definition: "to join something to something else" },
      { text: "it", startIndex: 17, endIndex: 19, saved: false },
      { text: "to", startIndex: 20, endIndex: 22, saved: false },
      { text: "my", startIndex: 23, endIndex: 25, saved: false },
      { text: "reading", startIndex: 26, endIndex: 33, saved: false },
      { text: "list", startIndex: 34, endIndex: 38, saved: false },
    ],
  },
  {
    id: 27,
    startTime: 102.5,
    endTime: 106,
    originalText: "Do you belong to any book clubs?",
    translatedText: "你参加过读书俱乐部吗？",
    words: [
      { text: "Do", startIndex: 0, endIndex: 2, saved: false },
      { text: "you", startIndex: 3, endIndex: 6, saved: false },
      { text: "belong", startIndex: 7, endIndex: 13, saved: true, difficulty: "intermediate", translation: "属于", definition: "to be a member of" },
      { text: "to", startIndex: 14, endIndex: 16, saved: false },
      { text: "any", startIndex: 17, endIndex: 20, saved: false },
      { text: "book", startIndex: 21, endIndex: 25, saved: false },
      { text: "clubs", startIndex: 26, endIndex: 31, saved: true, difficulty: "beginner", translation: "俱乐部", definition: "an association dedicated to a particular interest" },
    ],
  },
  {
    id: 28,
    startTime: 106.5,
    endTime: 110,
    originalText: "Yes, I joined one last year.",
    translatedText: "是的，我去年加入了一个。",
    words: [
      { text: "Yes", startIndex: 0, endIndex: 3, saved: false },
      { text: "I", startIndex: 5, endIndex: 6, saved: false },
      { text: "joined", startIndex: 7, endIndex: 13, saved: true, difficulty: "beginner", translation: "加入", definition: "to become a member of" },
      { text: "one", startIndex: 14, endIndex: 17, saved: false },
      { text: "last", startIndex: 18, endIndex: 22, saved: false },
      { text: "year", startIndex: 23, endIndex: 27, saved: false },
    ],
  },
  {
    id: 29,
    startTime: 110.5,
    endTime: 114,
    originalText: "We meet once a month to discuss books.",
    translatedText: "我们每月聚会一次讨论书籍。",
    words: [
      { text: "We", startIndex: 0, endIndex: 2, saved: false },
      { text: "meet", startIndex: 3, endIndex: 7, saved: true, difficulty: "beginner", translation: "见面", definition: "to come together" },
      { text: "once", startIndex: 8, endIndex: 12, saved: false },
      { text: "a", startIndex: 13, endIndex: 14, saved: false },
      { text: "month", startIndex: 15, endIndex: 20, saved: false },
      { text: "to", startIndex: 21, endIndex: 23, saved: false },
      { text: "discuss", startIndex: 24, endIndex: 31, saved: true, difficulty: "intermediate", translation: "讨论", definition: "to talk about something" },
      { text: "books", startIndex: 32, endIndex: 37, saved: false },
    ],
  },
  {
    id: 30,
    startTime: 114.5,
    endTime: 118,
    originalText: "That sounds like a lot of fun!",
    translatedText: "听起来很有趣！",
    words: [
      { text: "That", startIndex: 0, endIndex: 4, saved: false },
      { text: "sounds", startIndex: 5, endIndex: 11, saved: false },
      { text: "like", startIndex: 12, endIndex: 16, saved: false },
      { text: "a", startIndex: 17, endIndex: 18, saved: false },
      { text: "lot", startIndex: 19, endIndex: 22, saved: false },
      { text: "of", startIndex: 23, endIndex: 25, saved: false },
      { text: "fun", startIndex: 26, endIndex: 29, saved: true, difficulty: "beginner", translation: "乐趣", definition: "enjoyment or amusement" },
    ],
  },
];
